CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  location VARCHAR(100),
  github_username VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE languages (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  language VARCHAR(100) NOT NULL
);
